# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources: 
  repositories:
    - repository: GovernedTemplates
      type: git
      name: ProjToTest/ProjToTest
      ref: refs/heads/main

extends:
  template: v2/Microsoft.NonOfficial.yml@GovernedTemplates
  parameters:
      platform:
        name: m365
        workload: 'Substrate'
        serviceTreeId: "28a2529f-7085-4bbf-aa02-787135bb26a8"
        serviceGroupName: "Microsoft.O365.Cosmic.AppInfra"
      featureFlags: 
        enableCheckout: true
      stages:
      - stage: 'PROD_CosmicSetup'
        variables:
          stage_type: nonDeployment
        displayName: 'CosmicSetup'
        jobs:
        - job: SetupCosmicPipelineVariables
          pool: 
            type: release
          steps:
            - download: PrimaryArtifact 
            - task: comic_deployment_priming_prod_with_onebranch@0
              name: SetVar
              inputs:
                DeploymentParamtersFilePath: '$(PIPELINE.WORKSPACE)/PrimaryArtifact/drop_CosmicArtifact_CosmicArtifactJob/package/ModelService/ModelService-deployment-parameters.json'


# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
